# Site settings
author: Dayron Holguin
title: The Blueprint
header-img: img/home-bg.png
email: dayronholguin@yahoo.com
copyright_name: Dayron Holguin
description: > # this means to ignore newlines until "baseurl:"
  speak in codes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dayronholguin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
